version: 2.1

orbs:
  # orbsの名前は長くて面倒なのでエイリアスを付けて扱う↓
  aws-ecr: circleci/aws-ecr@8.1.0
  aws-ecs: circleci/aws-ecs@2.2.1

jobs:
  test_frontend:
    docker:
      - image: cimg/node:17.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: package install process
          command: yarn
      - save_cache:
          paths:
            - ~repo/node_modules
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: yarn test
          command: yarn test:ci

workflows:
  workflows_frontend_test_build_push_deploy:
    jobs:
      - test_frontend
      - aws-ecr/build-and-push-image:
          requires:
            - test_frontend
          region: AWS_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: 'ecs-sample-frontend-image'
          tag: '${CIRCLE_SHA1}'
          filters:
            branches:
              only:
                - main
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: 'ecs-sample-task-definition-frontend'
          cluster-name: 'ecs-sample-cluster'
          service-name: 'ecs-sample-service-frontend'
          container-image-name-updates: 'container=ecs-sample-container-frontend,tag=${CIRCLE_SHA1}'
          filters:
            branches:
              only:
                - main
